import { Aleo } from "next/font/google";
import "./globals.css";
import { Main } from "next/document";

const aleo = Aleo({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={aleo.className}>{children}
      <Header />
               {children}
      <Footer />
      </body>
    </html>
  );
}
